// Loads the bundled JSON data (generated by build-data.js) inside the extension.
// pokedex/moves are loaded once; sets files are loaded lazily per format and cached.
import { api } from './api.js';
const base = (p) => api.runtime.getURL(`data/${p}`);

let _pokedex = null;
let _moves = null;
let _abilitiesDesc = null;
const _setsCache = new Map();
const _itemsCache = new Map();
const _abilitiesCache = new Map();
const _teraCache = new Map();
const _statsCache = new Map();
const _movesFreqCache = new Map();

async function fetchJson(url) {
	try {
		const res = await fetch(url);
		console.log('[PSH data] fetch ' + url + ' → ' + res.status);
		if (!res.ok) throw new Error(`fetch ${url}: ${res.status}`);
		return res.json();
	} catch (e) {
		console.warn('[PSH data] fetch ' + url + ' FAIL', e);
		throw e;
	}
}

export async function loadCore() {
	if (!_pokedex) {
		// abilities-desc powers the ability descriptions in the panel; tolerate it missing (older
		// bundles) by falling back to {} so the rest of core still loads.
		[_pokedex, _moves, _abilitiesDesc] = await Promise.all([
			fetchJson(base('pokedex.json')),
			fetchJson(base('moves.json')),
			fetchJson(base('abilities-desc.json')).catch(() => ({})),
		]);
	}
	return { pokedex: _pokedex, moves: _moves, abilitiesDesc: _abilitiesDesc };
}

// Returns the sets object for a resolved key (e.g. "gen9doubles"), or null if unavailable.
export async function loadSets(key) {
	if (!key) return null;
	if (_setsCache.has(key)) return _setsCache.get(key);
	let sets = null;
	try {
		sets = await fetchJson(base(`sets/${key}.json`));
	} catch {
		sets = null; // format we don't ship data for
	}
	_setsCache.set(key, sets);
	return sets;
}

// Returns the predicted-item frequency table for a resolved key, or null if unavailable.
// Shape: { speciesId: { role: { itemName: count } } } — see build-data.js.
export async function loadItems(key) {
	if (!key) return null;
	if (_itemsCache.has(key)) return _itemsCache.get(key);
	let items = null;
	try {
		items = await fetchJson(base(`items/${key}.json`));
	} catch {
		items = null; // format/gen we don't ship item data for
	}
	_itemsCache.set(key, items);
	return items;
}

// Returns the predicted-ability frequency table for a resolved key, or null if unavailable.
// Shape: { speciesId: { role: { abilityName: count } } } — see build-data.js.
export async function loadAbilities(key) {
	if (!key) return null;
	if (_abilitiesCache.has(key)) return _abilitiesCache.get(key);
	let abilities = null;
	try {
		abilities = await fetchJson(base(`abilities/${key}.json`));
	} catch {
		abilities = null; // format/gen we don't ship ability data for
	}
	_abilitiesCache.set(key, abilities);
	return abilities;
}

// Returns the tera-type frequency table for a resolved key, or null if unavailable.
// Shape: { speciesId: { role: { teraType: count } } } — see build-data.js.
export async function loadTera(key) {
	if (!key) return null;
	if (_teraCache.has(key)) return _teraCache.get(key);
	let tera = null;
	try {
		tera = await fetchJson(base(`tera/${key}.json`));
	} catch {
		tera = null;
	}
	_teraCache.set(key, tera);
	return tera;
}

// Returns the move-frequency table for a resolved key, or null if unavailable.
// Shape: { speciesId: { role: { total: N, moves: { moveId: count } } } } — see build-data.js.
// total = times this role was rolled (denominator for both move freq and role freq).
export async function loadMovesFreq(key) {
	if (!key) return null;
	if (_movesFreqCache.has(key)) return _movesFreqCache.get(key);
	let movesFreq = null;
	try {
		movesFreq = await fetchJson(base(`moves-freq/${key}.json`));
	} catch {
		movesFreq = null;
	}
	_movesFreqCache.set(key, movesFreq);
	return movesFreq;
}

// Returns the pre-nature stat min/max table for a resolved key, or null if unavailable.
// Shape: { speciesId: { spe: {min, max}, atk: {min, max}, ... } } — see build-data.js.
export async function loadStats(key) {
	if (!key) return null;
	if (_statsCache.has(key)) return _statsCache.get(key);
	let stats = null;
	try {
		stats = await fetchJson(base(`stats/${key}.json`));
	} catch {
		stats = null;
	}
	_statsCache.set(key, stats);
	return stats;
}
